/// Upload options for file upload operations
class UploadOptions {
  /// Content type (MIME type)
  final String? contentType;

  /// Cache control header
  final String? cacheControl;

  /// Content disposition header
  final String? contentDisposition;

  /// Content encoding (e.g., gzip)
  final String? contentEncoding;

  /// Content language
  final String? contentLanguage;

  /// Custom metadata
  final Map<String, String>? customMetadata;

  const UploadOptions({
    this.contentType,
    this.cacheControl,
    this.contentDisposition,
    this.contentEncoding,
    this.contentLanguage,
    this.customMetadata,
  });

  /// Default options for public files
  static const public = UploadOptions(
    cacheControl: 'public, max-age=3600',
  );

  /// Default options for private files
  static const private = UploadOptions(
    cacheControl: 'private, max-age=3600',
  );

  /// Create a copy with updated fields
  UploadOptions copyWith({
    String? contentType,
    String? cacheControl,
    String? contentDisposition,
    String? contentEncoding,
    String? contentLanguage,
    Map<String, String>? customMetadata,
  }) {
    return UploadOptions(
      contentType: contentType ?? this.contentType,
      cacheControl: cacheControl ?? this.cacheControl,
      contentDisposition: contentDisposition ?? this.contentDisposition,
      contentEncoding: contentEncoding ?? this.contentEncoding,
      contentLanguage: contentLanguage ?? this.contentLanguage,
      customMetadata: customMetadata ?? this.customMetadata,
    );
  }
}

/// Configuration for Firebase Storage operations
///
/// Note: Firebase uses platform-specific configuration files
/// (google-services.json, GoogleService-Info.plist) for project setup.
/// This config is for storage-specific application settings.
class StorageConfig {
  /// Default bucket name for storage operations
  /// If null, uses the default Firebase Storage bucket
  final String? defaultBucket;

  /// Maximum file size in bytes (default: 100MB)
  final int maxFileSizeBytes;

  /// Allowed file extensions (null means all allowed)
  final List<String>? allowedExtensions;

  /// Enable debug logging
  final bool enableLogging;

  /// Default upload options
  final UploadOptions defaultUploadOptions;

  /// Timeout duration for upload operations
  final Duration uploadTimeout;

  /// Timeout duration for download operations
  final Duration downloadTimeout;

  /// Whether to automatically get download URLs after upload
  final bool autoGenerateDownloadUrl;

  /// Whether to validate file extensions
  final bool validateExtensions;

  /// Whether to validate file sizes
  final bool validateFileSize;

  const StorageConfig({
    this.defaultBucket,
    this.maxFileSizeBytes = 104857600, // 100MB
    this.allowedExtensions,
    this.enableLogging = false,
    this.defaultUploadOptions = UploadOptions.private,
    this.uploadTimeout = const Duration(minutes: 10),
    this.downloadTimeout = const Duration(minutes: 10),
    this.autoGenerateDownloadUrl = true,
    this.validateExtensions = true,
    this.validateFileSize = true,
  });

  /// Create default configuration
  factory StorageConfig.defaultConfig() {
    return const StorageConfig();
  }

  /// Create configuration for images only
  factory StorageConfig.imagesOnly({
    String? defaultBucket,
    int maxFileSizeBytes = 10485760, // 10MB
  }) {
    return StorageConfig(
      defaultBucket: defaultBucket,
      maxFileSizeBytes: maxFileSizeBytes,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg'],
      defaultUploadOptions: UploadOptions.public,
    );
  }

  /// Create configuration for documents only
  factory StorageConfig.documentsOnly({
    String? defaultBucket,
    int maxFileSizeBytes = 52428800, // 50MB
  }) {
    return StorageConfig(
      defaultBucket: defaultBucket,
      maxFileSizeBytes: maxFileSizeBytes,
      allowedExtensions: [
        'pdf',
        'doc',
        'docx',
        'xls',
        'xlsx',
        'ppt',
        'pptx',
        'txt',
        'csv'
      ],
      defaultUploadOptions: UploadOptions.private,
    );
  }

  /// Create configuration for media files
  factory StorageConfig.mediaOnly({
    String? defaultBucket,
    int maxFileSizeBytes = 524288000, // 500MB
  }) {
    return StorageConfig(
      defaultBucket: defaultBucket,
      maxFileSizeBytes: maxFileSizeBytes,
      allowedExtensions: [
        // Images
        'jpg',
        'jpeg',
        'png',
        'gif',
        'webp',
        'bmp',
        'svg',
        // Videos
        'mp4',
        'avi',
        'mov',
        'wmv',
        'flv',
        'webm',
        'mkv',
        // Audio
        'mp3',
        'wav',
        'ogg',
        'flac',
        'aac',
        'm4a',
        'wma',
      ],
      defaultUploadOptions: UploadOptions.public,
    );
  }

  /// Validate if a file extension is allowed
  bool isExtensionAllowed(String extension) {
    if (!validateExtensions || allowedExtensions == null) return true;
    return allowedExtensions!.contains(extension.toLowerCase());
  }

  /// Validate if a file size is within limits
  bool isFileSizeAllowed(int sizeInBytes) {
    if (!validateFileSize) return true;
    return sizeInBytes <= maxFileSizeBytes;
  }

  /// Get human-readable max file size
  String get formattedMaxFileSize {
    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    var fileSize = maxFileSizeBytes.toDouble();
    var unitIndex = 0;

    while (fileSize >= 1024 && unitIndex < units.length - 1) {
      fileSize /= 1024;
      unitIndex++;
    }

    return '${fileSize.toStringAsFixed(2)} ${units[unitIndex]}';
  }

  /// Create a copy with updated fields
  StorageConfig copyWith({
    String? defaultBucket,
    int? maxFileSizeBytes,
    List<String>? allowedExtensions,
    bool? enableLogging,
    UploadOptions? defaultUploadOptions,
    Duration? uploadTimeout,
    Duration? downloadTimeout,
    bool? autoGenerateDownloadUrl,
    bool? validateExtensions,
    bool? validateFileSize,
  }) {
    return StorageConfig(
      defaultBucket: defaultBucket ?? this.defaultBucket,
      maxFileSizeBytes: maxFileSizeBytes ?? this.maxFileSizeBytes,
      allowedExtensions: allowedExtensions ?? this.allowedExtensions,
      enableLogging: enableLogging ?? this.enableLogging,
      defaultUploadOptions: defaultUploadOptions ?? this.defaultUploadOptions,
      uploadTimeout: uploadTimeout ?? this.uploadTimeout,
      downloadTimeout: downloadTimeout ?? this.downloadTimeout,
      autoGenerateDownloadUrl:
          autoGenerateDownloadUrl ?? this.autoGenerateDownloadUrl,
      validateExtensions: validateExtensions ?? this.validateExtensions,
      validateFileSize: validateFileSize ?? this.validateFileSize,
    );
  }

  @override
  String toString() {
    return 'StorageConfig(bucket: ${defaultBucket ?? "default"}, '
        'maxSize: $formattedMaxFileSize, '
        'extensions: ${allowedExtensions?.length ?? "all"})';
  }
}
