/// UPI payment request model
library;

/// UPI payment request for initiating a transaction
class UpiPaymentRequest {
  /// Payee VPA (UPI ID) - e.g., merchant@upi, shop@paytm
  final String payeeVpa;

  /// Payee name (merchant/business name)
  final String payeeName;

  /// Unique transaction identifier (generated by your app)
  final String transactionId;

  /// Transaction reference ID (can be same as transactionId)
  final String transactionRef;

  /// Payment amount in INR
  final double amount;

  /// Currency code (default: INR)
  final String currency;

  /// Transaction description/note
  final String transactionNote;

  /// Merchant category code (optional)
  final String? merchantCode;

  /// Callback URL (optional)
  final String? url;

  /// Minimum amount in INR (0.01)
  static const double minAmount = 0.01;

  /// Maximum amount in INR (1,00,000)
  static const double maxAmount = 100000.00;

  UpiPaymentRequest({
    required this.payeeVpa,
    required this.payeeName,
    required this.transactionId,
    required this.transactionRef,
    required this.amount,
    this.currency = 'INR',
    required this.transactionNote,
    this.merchantCode,
    this.url,
  });

  /// Validate the payment request
  bool get isValid {
    if (payeeVpa.isEmpty) return false;
    if (payeeName.isEmpty) return false;
    if (transactionId.isEmpty) return false;
    if (transactionRef.isEmpty) return false;
    if (amount < minAmount || amount > maxAmount) return false;
    if (transactionNote.isEmpty) return false;
    if (!_isValidVpa(payeeVpa)) return false;
    return true;
  }

  /// Get validation error message
  String? get validationError {
    if (payeeVpa.isEmpty) return 'Payee VPA is required';
    if (!_isValidVpa(payeeVpa)) return 'Invalid VPA format';
    if (payeeName.isEmpty) return 'Payee name is required';
    if (transactionId.isEmpty) return 'Transaction ID is required';
    if (transactionRef.isEmpty) return 'Transaction reference is required';
    if (amount < minAmount) return 'Amount must be at least ₹$minAmount';
    if (amount > maxAmount) return 'Amount cannot exceed ₹$maxAmount';
    if (transactionNote.isEmpty) return 'Transaction note is required';
    return null;
  }

  /// Validate VPA format (e.g., username@bankname)
  static bool _isValidVpa(String vpa) {
    final vpaRegex = RegExp(r'^[\w.-]+@[\w]+$');
    return vpaRegex.hasMatch(vpa);
  }

  /// Format amount for display
  String get formattedAmount => '₹${amount.toStringAsFixed(2)}';

  /// Create UPI deep link
  String toUpiDeepLink() {
    final params = {
      'pa': payeeVpa,
      'pn': Uri.encodeComponent(payeeName),
      'tid': transactionId,
      'tr': transactionRef,
      'tn': Uri.encodeComponent(transactionNote),
      'am': amount.toStringAsFixed(2),
      'cu': currency,
    };

    if (merchantCode != null && merchantCode!.isNotEmpty) {
      params['mc'] = merchantCode!;
    }

    if (url != null && url!.isNotEmpty) {
      params['url'] = Uri.encodeComponent(url!);
    }

    final queryString = params.entries.map((e) => '${e.key}=${e.value}').join('&');
    return 'upi://pay?$queryString';
  }

  /// Copy with modifications
  UpiPaymentRequest copyWith({
    String? payeeVpa,
    String? payeeName,
    String? transactionId,
    String? transactionRef,
    double? amount,
    String? currency,
    String? transactionNote,
    String? merchantCode,
    String? url,
  }) {
    return UpiPaymentRequest(
      payeeVpa: payeeVpa ?? this.payeeVpa,
      payeeName: payeeName ?? this.payeeName,
      transactionId: transactionId ?? this.transactionId,
      transactionRef: transactionRef ?? this.transactionRef,
      amount: amount ?? this.amount,
      currency: currency ?? this.currency,
      transactionNote: transactionNote ?? this.transactionNote,
      merchantCode: merchantCode ?? this.merchantCode,
      url: url ?? this.url,
    );
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      'payeeVpa': payeeVpa,
      'payeeName': payeeName,
      'transactionId': transactionId,
      'transactionRef': transactionRef,
      'amount': amount,
      'currency': currency,
      'transactionNote': transactionNote,
      'merchantCode': merchantCode,
      'url': url,
    };
  }

  /// Create from JSON
  factory UpiPaymentRequest.fromJson(Map<String, dynamic> json) {
    return UpiPaymentRequest(
      payeeVpa: json['payeeVpa'] as String,
      payeeName: json['payeeName'] as String,
      transactionId: json['transactionId'] as String,
      transactionRef: json['transactionRef'] as String,
      amount: (json['amount'] as num).toDouble(),
      currency: json['currency'] as String? ?? 'INR',
      transactionNote: json['transactionNote'] as String,
      merchantCode: json['merchantCode'] as String?,
      url: json['url'] as String?,
    );
  }

  @override
  String toString() {
    return 'UpiPaymentRequest(vpa: $payeeVpa, amount: $formattedAmount, txnId: $transactionId)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is UpiPaymentRequest && other.transactionId == transactionId;
  }

  @override
  int get hashCode => transactionId.hashCode;
}
