/// Flutter Offline Support Module
///
/// A production-ready offline support and connectivity management solution
library offline_support;

// Models
export 'models/connectivity_state.dart';
export 'models/cache_metadata.dart';
export 'models/offline_request.dart';
export 'models/sync_result.dart';
export 'models/network_request_info.dart';

// Exceptions
export 'exceptions/offline_exception.dart';
export 'exceptions/cache_exception.dart';
export 'exceptions/sync_exception.dart';

// Configuration
export 'config/offline_config.dart';
export 'config/cache_policy.dart';
export 'config/sync_policy.dart';

// Core exports (commented out - implement as needed)
// export 'core/connectivity/connectivity_manager.dart';
// export 'core/cache/cache_service.dart';
// export 'core/http/offline_http_client.dart';
// export 'core/queue/request_queue.dart';
// export 'core/sync/sync_manager.dart';

// Widgets (commented out - implement as needed)
// export 'widgets/offline_banner.dart';
// export 'widgets/connectivity_aware_widget.dart';
// export 'widgets/sync_indicator.dart';

import 'package:hive_flutter/hive_flutter.dart';
import 'models/cache_metadata.dart';
import 'models/offline_request.dart';
import 'config/offline_config.dart';

/// Main entry point for the Offline Support module
class OfflineSupport {
  static OfflineSupport? _instance;
  static OfflineConfig? _config;

  OfflineSupport._internal();

  /// Get the singleton instance
  static OfflineSupport get instance {
    _instance ??= OfflineSupport._internal();
    return _instance!;
  }

  /// Get the current configuration
  static OfflineConfig get config {
    if (_config == null) {
      throw StateError('OfflineSupport has not been initialized. Call OfflineSupport.initialize() first.');
    }
    return _config!;
  }

  /// Register Hive type adapters
  static Future<void> registerHiveAdapters() async {
    // Register adapters generated by build_runner
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(CacheMetadataAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(CacheEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(3)) {
      Hive.registerAdapter(OfflineRequestAdapter());
    }
  }

  /// Initialize the offline support module
  static Future<void> initialize({
    OfflineConfig? config,
  }) async {
    _config = config ?? const OfflineConfig();

    // Ensure Hive is initialized
    if (!Hive.isBoxOpen('offline_cache')) {
      await Hive.initFlutter();
    }

    // Register adapters
    await registerHiveAdapters();

    // Open required boxes
    await Hive.openBox('offline_cache');
    await Hive.openBox('offline_queue');
    await Hive.openBox('offline_metadata');

    if (_config!.debugMode) {
      print('[OfflineSupport] Module initialized successfully');
      print('[OfflineSupport] Config: $_config');
    }
  }

  /// Dispose and cleanup resources
  static Future<void> dispose() async {
    await Hive.close();
    _instance = null;
    _config = null;
  }

  /// Clear all offline data
  static Future<void> clearAllData() async {
    final cacheBox = Hive.box('offline_cache');
    final queueBox = Hive.box('offline_queue');
    final metadataBox = Hive.box('offline_metadata');

    await cacheBox.clear();
    await queueBox.clear();
    await metadataBox.clear();

    if (config.debugMode) {
      print('[OfflineSupport] All offline data cleared');
    }
  }
}
